name: CI Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # GitHub Actions의 기본 설정을 사용하여 리포지토리를 체크아웃
      - uses: actions/checkout@v4

      # Node.js를 설치하고 npm 캐시를 사용하도록 설정
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "npm"

      # npm 패키지들을 설치
      - run: npm ci

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Docker Hub 연동
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t gwonu/project ./proxy

      - name: Push docker image
        run: docker push gwonu/project:latest